import './globals.css';
import 'react-loading-skeleton/dist/skeleton.css';
import AuthProvider from './components/AuthProvider/AuthProvider';
import { getServerSession } from 'next-auth';
import { BlogProvider } from './context/BlogProvider';
import BottomMenu from './components/ui/BottomMenu';
import { SkeletonTheme } from 'react-loading-skeleton';
import { Fredoka  } from 'next/font/google';

const fredoka = Fredoka({ subsets: ['latin'], weight: ['400'] });

export const metadata = {
  title: 'JobSpace',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();

  return (
    <html lang="en" className={fredoka.className}>
      <body>
        <SkeletonTheme baseColor="#202020" highlightColor="#444">
          <BlogProvider>
            <AuthProvider session={session}>
              <div className="lg:hidden">
                <BottomMenu />
              </div>
              <div className="">{children}</div>
              <div className="hidden lg:flex">
              </div>
            </AuthProvider>
          </BlogProvider>
        </SkeletonTheme>
      </body>
    </html>
  );
}
